// BrailleMapping.tsx

type BrailleMapping = {
  [key: string]: {
    braille: string;
    keyMapping: number;
    dotPattern: number[];
  };
};

// Initialize and declare the ASCII to Braille map
export const asciiBraille: BrailleMapping = {
  "0": { braille: "⠴", keyMapping: 52, dotPattern: [3, 5, 6] },
  "1": { braille: "⠂", keyMapping: 2, dotPattern: [2] },
  "2": { braille: "⠆", keyMapping: 6, dotPattern: [2, 3] },
  "3": { braille: "⠒", keyMapping: 18, dotPattern: [2, 5] },
  "4": { braille: "⠲", keyMapping: 50, dotPattern: [2, 5, 6]},
  "5": { braille: "⠢", keyMapping: 34, dotPattern: [2, 6] },
  "6": { braille: "⠖", keyMapping: 22, dotPattern: [2, 3, 5] },
  "7": { braille: "⠶", keyMapping: 54, dotPattern: [2, 3, 5, 6] },
  "8": { braille: "⠦", keyMapping: 38, dotPattern: [2, 3, 6] },
  "9": { braille: "⠔", keyMapping: 20, dotPattern: [3, 5] },
  " ": { braille: "⠀", keyMapping: 0, dotPattern: [] },
  "!": { braille: "⠮", keyMapping: 46, dotPattern: [2, 3, 4, 6] },
  '"': { braille: "⠐", keyMapping: 16, dotPattern: [5] },
  "#": { braille: "⠼", keyMapping: 60, dotPattern: [3, 4, 5, 6] },
  $: { braille: "⠫", keyMapping: 43, dotPattern: [1, 2, 4, 6] },
  "%": { braille: "⠩", keyMapping: 41, dotPattern: [1, 4, 6] },
  "&": { braille: "⠯", keyMapping: 47, dotPattern: [1, 2, 3, 4, 6] },
  "'": { braille: "⠄", keyMapping: 4, dotPattern: [3] },
  "(": { braille: "⠷", keyMapping: 55, dotPattern: [1, 2, 3, 5, 6] },
  ")": { braille: "⠾", keyMapping: 62, dotPattern: [2, 3, 4, 5, 6] },
  "*": { braille: "⠡", keyMapping: 33, dotPattern: [1, 6] },
  "+": { braille: "⠬", keyMapping: 44, dotPattern: [3, 4, 6] },
  ",": { braille: "⠠", keyMapping: 32, dotPattern: [6] },
  "-": { braille: "⠤", keyMapping: 36, dotPattern: [3, 6] },
  ".": { braille: "⠨", keyMapping: 40, dotPattern: [4, 6] },
  "/": { braille: "⠌", keyMapping: 12, dotPattern: [3, 4] },
  ":": { braille: "⠱", keyMapping: 49, dotPattern: [1, 5, 6] },
  ";": { braille: "⠰", keyMapping: 48, dotPattern: [5, 6] },
  "<": { braille: "⠣", keyMapping: 35, dotPattern: [1, 2, 6] },
  "=": { braille: "⠿", keyMapping: 63, dotPattern: [1, 2, 3, 4, 5, 6] },
  ">": { braille: "⠜", keyMapping: 28, dotPattern: [3, 4, 5] },
  "?": { braille: "⠹", keyMapping: 57, dotPattern: [1, 4, 5, 6] },
  "`": { braille: "⠈", keyMapping: 8, dotPattern: [4] },
  a: { braille: "⠁", keyMapping: 1, dotPattern: [1] },
  b: { braille: "⠃", keyMapping: 3, dotPattern: [1, 2] },
  c: { braille: "⠉", keyMapping: 9, dotPattern: [1, 4] },
  d: { braille: "⠙", keyMapping: 25, dotPattern: [1, 4, 5] },
  e: { braille: "⠑", keyMapping: 17, dotPattern: [1, 5] },
  f: { braille: "⠋", keyMapping: 11, dotPattern: [1, 2, 4] },
  g: { braille: "⠛", keyMapping: 27, dotPattern: [1, 2, 4, 5] },
  h: { braille: "⠓", keyMapping: 19, dotPattern: [1, 2, 5] },
  i: { braille: "⠊", keyMapping: 10, dotPattern: [2, 4] },
  j: { braille: "⠚", keyMapping: 26, dotPattern: [2, 4, 5] },
  k: { braille: "⠅", keyMapping: 5, dotPattern: [1, 3] },
  l: { braille: "⠇", keyMapping: 7, dotPattern: [1, 2, 3] },
  m: { braille: "⠍", keyMapping: 13, dotPattern: [1, 3, 4] },
  n: { braille: "⠝", keyMapping: 29, dotPattern: [1, 3, 4, 5] },
  o: { braille: "⠕", keyMapping: 21, dotPattern: [1, 3, 5] },
  p: { braille: "⠏", keyMapping: 15, dotPattern: [1, 2, 3, 4] },
  q: { braille: "⠟", keyMapping: 31, dotPattern: [1, 2, 3, 4, 5] },
  r: { braille: "⠗", keyMapping: 23, dotPattern: [1, 2, 3, 5] },
  s: { braille: "⠎", keyMapping: 14, dotPattern: [2, 3, 4] },
  t: { braille: "⠞", keyMapping: 30, dotPattern: [2, 3, 4, 5] },
  u: { braille: "⠥", keyMapping: 37, dotPattern: [1, 3, 6] },
  v: { braille: "⠧", keyMapping: 39, dotPattern: [1, 2, 3, 6] },
  w: { braille: "⠺", keyMapping: 58, dotPattern: [2, 4, 5, 6] },
  x: { braille: "⠭", keyMapping: 45, dotPattern: [1, 3, 4, 6] },
  y: { braille: "⠽", keyMapping: 61, dotPattern: [1, 3, 4, 5, 6] },
  z: { braille: "⠵", keyMapping: 53, dotPattern: [1, 3, 5, 6] },
  "{": { braille: "⠪", keyMapping: 42, dotPattern: [2, 4, 6] },
  "|": { braille: "⠳", keyMapping: 51, dotPattern: [1, 2, 5, 6] },
  "}": { braille: "⠻", keyMapping: 59, dotPattern: [1, 2, 4, 5, 6] },
  "~": { braille: "⠘", keyMapping: 24, dotPattern: [4, 5] },
  "_": { braille: "⠸", keyMapping: 56, dotPattern: [4, 5, 6]},
};
